### PR TITLE
Forgot password 

### PR DESCRIPTION
**Pull request by hamzahalilovic**
Forgot password user story flow
added new background.png used as Background
updated icons in password input field

### CODE REVIEW

**Comment by prifina-admin** [comment]
Could you replace, that checkmark asset with iconify (blend-icon) checkmark...

import bxCheckCircle from '@iconify-icons/bx/bx-check-circle';

**Comment by prifina-admin** [comment]
Also include the storybook story, so it is possible to check without app... in this case it is not so important as this is unauthenticated route, but normally testing would be easier using the story.

**Comment by prifina-admin** [comment]
Also include the user story doc link... (google doc), what you have used.... so it is quicker to find.

**Comment by prifina-admin** [comment]
Also try eslint before PR.... :)

**Comment by hamzahalilovic** [comment]
> Could you replace, that checkmark asset with iconify (blend-icon) checkmark...
> 
> import bxCheckCircle from '@iconify-icons/bx/bx-check-circle';

**Comment by hamzahalilovic** [comment]
> Could you replace, that checkmark asset with iconify (blend-icon) checkmark...
> 
> import bxCheckCircle from '@iconify-icons/bx/bx-check-circle';

Resolved

**Comment by hamzahalilovic** [comment]
> Also include the storybook story, so it is possible to check without app... in this case it is not so important as this is unauthenticated route, but normally testing would be easier using the story.

The story file is available under ForgotPassword.stories.js

**Comment by hamzahalilovic** [comment]
> Also include the user story doc link... (google doc), what you have used.... so it is quicker to find.

I've linked the user story to the PR so it can now be found there :)

**Review by prifina-admin — APPROVED** [review]

**Pull request merged**
